name: ChuyenPhatNhanh
version: '${version}'
main: me.lethinh.chuyenphatnhanh.ChuyenPhatNhanh
depend: [PlayerPoints]

commands:
  chuyenitem:
    description: Transfer
    usage: /<command>
  nhanitem:
    description: Receive
    usage: /<command>
